print("=== THREAT HUNTING SCENARIO ===")
print("1. Attacker reconnaissance detected:")
print("   - Port scanning on ports 22, 80, 443, 3389")
print("2. DNS enumeration attempts:")
print("   - Multiple subdomain queries")
print("3. Honeypot engagement:")
print("   - Queries for admin, vpn, database")
print("\nTHREAT SCORE: 8.5/10")
print("RECOMMENDATION: Block source IP, review firewall logs")
